extern crate cc;
fn main() {
    cc::Build::new()
        .include("apron/num")
        .include("apron/apron")
        .include("apron/itv")
        .include("apron/box")
        .include("/usr/include")
//        .compiler("/usr/local/Cellar/gcc@5/5.5.0_2/bin/gcc-5")
        .flag("-std=c99").flag("-U__STRICT_ANSI__").flag("-fPIC").flag("-g").flag("-O0").flag("-UNDEBUG").flag("-DNUM_MPZ").flag("-Wno-everything")
//        .file("apron/apron/ap_linearize_aux.c")
        .file("apron/apron/ap_interval.c")
        .file("apron/apron/ap_scalar.c")
        .file("apron/apron/ap_linexpr1.c")
        .file("apron/apron/ap_manager.c")
        .file("apron/apron/ap_reducedproduct.c")
        .file("apron/apron/ap_lincons1.c")
        .file("apron/apron/ap_dimension.c")
        .file("apron/apron/ap_var.c")
//        .file("apron/apron/test_texpr0.c")
        .file("apron/apron/ap_generator1.c")
        .file("apron/apron/ap_texpr0.c")
//        .file("apron/apron/ap_linearize.c")
        .file("apron/apron/ap_tcons0.c")
        .file("apron/apron/ap_policy.c")
        .file("apron/apron/ap_generic.c")
        .file("apron/apron/ap_coeff.c")
        .file("apron/apron/ap_abstract0.c")
        .file("apron/apron/ap_texpr1.c")
        .file("apron/apron/ap_environment.c")
        .file("apron/apron/ap_tcons1.c")
        .file("apron/apron/ap_abstract1.c")
        .file("apron/apron/ap_linexpr0.c")
        .file("apron/apron/ap_disjunction.c")
        .file("apron/apron/ap_lincons0.c")
        .file("apron/apron/ap_generator0.c")
        .file("apron/box/box_resize.c")
        .file("apron/box/box_internal.c")
        .file("apron/box/box_representation.c")
        .file("apron/box/box_otherops.c")
        .file("apron/box/box_assign.c")
        .file("apron/box/box_meetjoin.c")
        .file("apron/box/box_constructor.c")
        .file("apron/box/box_policy.c")
//        .file("apron/num/essai.c")
//        .file("apron/num/test.c")
//        .file("apron/taylor1plus/t1p_resize.c")
//        .file("apron/taylor1plus/t1p_constructor.c")
//        .file("apron/taylor1plus/t1p_itv_utils.c")
//        .file("apron/taylor1plus/t1p_test_eval_texp.c")
//        .file("apron/taylor1plus/t1p_fun.c")
//        .file("apron/taylor1plus/t1p_representation.c")
//        .file("apron/taylor1plus/t1p_meetjoin.c")
//        .file("apron/taylor1plus/t1p_test.c")
//        .file("apron/taylor1plus/t1p_assign.c")
//        .file("apron/taylor1plus/t1p_otherops.c")
//        .file("apron/taylor1plus/t1p_internal.c")
        .file("apron/itv/itv_linearize.c")
        .file("apron/itv/itv.c")
        .file("apron/itv/itv_linexpr.c")
//        .file("apron/itv/test.c")
//        .file("apron/itv/test2.c")
//        .file("apron/octagons/oct_representation.c")
//        .file("apron/octagons/oct_nary.c")
//        .file("apron/octagons/oct_transfer.c")
//        .file("apron/octagons/oct_print.c")
//        .file("apron/octagons/oct_resize.c")
//        .file("apron/octagons/oct_predicate.c")
//        .file("apron/octagons/oct_test.c")
//        .file("apron/octagons/oct_hmat.c")
//        .file("apron/octagons/oct_closure.c")
//        .file("apron/newpolka/mf_qsort.c")
//        .file("apron/newpolka/pk_closure.c")
//        .file("apron/newpolka/pk_project.c")
//        .file("apron/newpolka/pkeq.c")
//        .file("apron/newpolka/pk_assign.c")
//        .file("apron/newpolka/pk_internal.c")
//        .file("apron/newpolka/test_environment.c")
//        .file("apron/newpolka/pk_user.c")
//        .file("apron/newpolka/pk_extract.c")
//        .file("apron/newpolka/pk_approximate.c")
//        .file("apron/newpolka/pk_matrix.c")
//        .file("apron/newpolka/test0.c")
//        .file("apron/newpolka/pk_constructor.c")
//        .file("apron/newpolka/pk_representation.c")
//        .file("apron/newpolka/pk_meetjoin.c")
//        .file("apron/newpolka/test1.c")
//        .file("apron/newpolka/pk_test.c")
//        .file("apron/newpolka/pk_resize.c")
//        .file("apron/newpolka/test.c")
//        .file("apron/newpolka/pk_satmat.c")
//        .file("apron/newpolka/pk_widening.c")
//        .file("apron/newpolka/pk_vector.c")
//        .file("apron/newpolka/pk_expandfold.c")
//        .file("apron/newpolka/pk_bit.c")
//        .file("apron/newpolka/pk_cherni.c")
        .compile("apron");
}
